"""Constantes de palavras-chave e patterns usadas pelo router."""

from __future__ import annotations


PROMPT_INJECTION_PATTERNS = (
    r"\b(?:ignore|disregard|override|bypass)\b.{0,80}\b(?:instruction|instructions|prompt|system|developer|rules?)\b",
    r"\b(?:desconsidere|ignore|ignore todas|ignore todos|ignore as|ignore os|burle|contorne)\b.{0,80}\b(?:instrucoes|instrução|instrucao|regras?|prompt|sistema|desenvolvedor|developer)\b",
    r"\b(?:revele|mostre|exiba|imprima|print|display)\b.{0,80}\b(?:prompt|system prompt|mensagem de sistema|developer message|mensagem do desenvolvedor)\b",
    r"\b(?:nao use|nao utilize|do not use|never use)\b.{0,30}\b(?:todas as tools|todas as ferramentas|any tools|nenhuma tool)\b",
)

SECRETARIAS_CONHECIDAS = (
    "saude",
    "educacao",
    "obras",
    "financas",
    "administracao",
    "procuradoria",
    "assistencia social",
    "meio ambiente",
    "planejamento",
    "transporte",
)

SUPPORTED_SCOPE_STRONG_KEYWORDS = (
    "prefeitura",
    "municipal",
    "receita",
    "receitas",
    "arrecadacao",
    "arrecadacoes",
    "arrecadado",
    "arrecadada",
    "arrecadou",
    "lancamento",
    "lancamentos",
    "lancado",
    "lancada",
    "tributo",
    "tributos",
    "imposto",
    "impostos",
    "iptu",
    "iss",
    "issqn",
    "itbi",
    "ipva",
    "fundeb",
    "divida ativa",
    "cobranca judicial",
    "licitacao",
    "licitacoes",
    "pregao",
    "pregoes",
    "edital",
    "editais",
    "fornecedor",
    "fornecedores",
    "vencedor",
    "vencedores",
    "contrato",
    "contratos",
    "contratado",
    "contratada",
    "contratados",
    "contratadas",
    "instrumento",
    "instrumentos",
    "planejamento",
    "planejamentos",
    "orcamento",
    "orcamentario",
    "orcamentaria",
    "dotacao",
    "empenhado",
    "liquidado",
    "servidor",
    "servidores",
    "funcionario",
    "funcionarios",
    "secretaria",
    "secretarias",
    "cargo",
    "cargos",
    "folha",
    "pagamento",
    "pagamentos",
    "fumusa",
    "despesa",
    "despesas",
    "empenho",
    "empenhos",
    "restos a pagar",
    "resto a pagar",
    "documento extra",
    "documentos extras",
    "diaria",
    "diarias",
    "passagem",
    "passagens",
    "estoque",
    "estoques",
    "almoxarifado",
    "saldo em estoque",
    "saldo de material",
    "movimentacao de estoque",
    "movimentacoes de estoque",
    "locomocao",
    "despesas com locomocao",
    "transferencia",
    "transferencias",
    "transferencia financeira",
    "transferencias financeiras",
    "transferido",
    "transferida",
    "repasse",
    "repasses",
    "repassado",
    "repassada",
    "repassou",
    "recebimento",
    "recebimentos",
    "devolucao",
    "devolucoes",
    "emenda",
    "emendas",
    "parlamentar",
    "parlamentares",
    "transferencia especial",
    "credor",
    "credores",
    "frota",
    "frotas",
    "veiculo",
    "veiculos",
    "carros",
    "patrimonio",
    "patrimonios",
    "bens patrimoniais",
    "placa",
    "vagas",
    "vaga",
    "regime",
    "quadro pessoal",
    "quadro de pessoal",
    "vereador",
    "vereadores",
    "prefeito",
    "prefeitos",
    "prefeita",
    "prefeitas",
    "viceprefeito",
    "vice-prefeito",
    "camara",
    "câmara",
    "eleito",
    "eleitos",
    "mandato",
    "mandatos",
    "legislatura",
    "legislaturas",
    "despesas por funcao",
    "dotacao inicial",
    "dotacao atualizada",
    "creditos adicionais",
)

SUPPORTED_SCOPE_WEAK_KEYWORDS = (
    "salario",
    "salarios",
    "recebeu",
    "recebe",
    "investimento",
    "investimentos",
    "investido",
    "investida",
    "arrecadado",
    "arrecadou",
    "lancado",
    "lancou",
    "gasto",
    "gastos",
    "pago",
    "pagos",
    "trabalha",
    "trabalham",
    "saude",
    "educacao",
    "urbanismo",
    "assistencia",
    "assistencia social",
    "cultura",
    "habitacao",
    "saneamento",
    "transporte",
    "meio ambiente",
    "ambiental",
    "agricultura",
    "esporte",
    "lazer",
    "seguranca",
    "previdencia",
    "cidadania",
    "legislativo",
    "obras",
    "procuradoria",
    "partido",
    "partidos",
)

DESPESAS_DOMAIN_KEYWORDS = (
    "despesa",
    "despesas",
    "empenho",
    "empenhos",
    "restos a pagar",
    "resto a pagar",
    "documento extra",
    "documentos extras",
    "credor",
    "credores",
)

DIARIAS_DOMAIN_KEYWORDS = (
    "diaria",
    "diarias",
    "adiantamento de viagem",
    "adiantamentos de viagem",
)

PASSAGENS_DOMAIN_KEYWORDS = (
    "passagem",
    "passagens",
    "viagem",
    "viagens",
    "locomocao",
    "despesas com locomocao",
)

ESTOQUES_DOMAIN_KEYWORDS = (
    "estoque",
    "estoques",
    "almoxarifado",
    "saldo em estoque",
    "saldo de material",
    "movimentacao de estoque",
    "movimentacoes de estoque",
)

DESPESAS_POR_FUNCAO_DOMAIN_KEYWORDS = (
    "despesas por funcao",
    "relatorio de despesas por funcao",
    "relatorio despesas por funcao",
)

TRANSFERENCIAS_FINANCEIRAS_DOMAIN_KEYWORDS = (
    "transferencia",
    "transferencias",
    "transferencia financeira",
    "transferencias financeiras",
    "transferido",
    "transferida",
    "repasse",
    "repasses",
    "repassado",
    "repassada",
    "repassou",
    "recebimento",
    "recebimentos",
    "devolucao",
    "devolucoes",
    "emenda",
    "emendas",
    "ementa",
    "ementas",
    "parlamentar",
    "parlamentares",
    "transferencia especial",
)

PATRIMONIOS_DOMAIN_KEYWORDS = (
    "patrimonio",
    "patrimonios",
    "bens patrimoniais",
    "patrimonial",
    "patrimoniais",
    "placa",
    "localizacao",
)

QUADRO_PESSOAL_DOMAIN_KEYWORDS = (
    "quadro pessoal",
    "quadro de pessoal",
    "vagas",
    "vaga",
    "regime",
    "regime de contratacao",
)

ELEITOS_DOMAIN_KEYWORDS = (
    "vereador",
    "vereadores",
    "prefeito",
    "prefeitos",
    "viceprefeito",
    "viceprefeita",
    "vice-prefeito",
    "prefeita",
    "prefeitas",
    "camara",
    "câmara",
    "eleito",
    "eleitos",
    "mandato",
    "mandatos",
    "legislatura",
    "legislaturas",
    "partido",
    "partidos",
)

LICITACOES_DOMAIN_KEYWORDS = (
    "licitacao",
    "licitacoes",
    "pregao",
    "pregoes",
    "edital",
    "editais",
    "instrumento",
    "instrumentos",
)

CONTRATOS_DOMAIN_KEYWORDS = (
    "contrato",
    "contratos",
    "contratado",
    "contratada",
    "contratados",
    "contratadas",
)

RECEITAS_DOMAIN_KEYWORDS = (
    "receita",
    "receitas",
    "arrecadacao",
    "arrecadacoes",
    "arrecadado",
    "arrecadada",
    "arrecadou",
    "lancamento",
    "lancamentos",
    "lancado",
    "lancada",
    "tributo",
    "tributos",
    "imposto",
    "impostos",
    "iptu",
    "iss",
    "issqn",
    "itbi",
    "ipva",
    "fundeb",
    "divida ativa",
    "cobranca judicial",
)

PLANEJAMENTO_DIRECT_KEYWORDS = (
    "planejamento",
    "planejamentos",
    "orcamento",
    "orcamentario",
    "orcamentaria",
    "dotacao",
    "empenhado",
    "liquidado",
    "investimento",
    "investimentos",
)

PLANEJAMENTO_ENTITY_HINT_KEYWORDS = (
    "planejado",
    "planejada",
    "recurso",
    "recursos",
    "verba",
    "verbas",
    "programa",
    "acao",
    "acoes",
    "gasto",
    "gastos",
    "pago",
    "pagos",
    "investido",
    "investida",
    "investimento",
    "investimentos",
)
